Repository django-wiki/django-wiki, pull requests merged in 2018-02, with the labels that each got.

#830 Use AppConfig.ready to check for sorl.thumbnail in images plugin.
  src/wiki/plugins/images/apps.py
  src/wiki/plugins/images/checks.py
  src/wiki/plugins/images/models.py
Labels: clean-up, enhancement

#829 Deleted duplicated lines in models/article.py
  src/wiki/models/article.py
Labels: clean-up

#831 Use --check option to check for test project's migrations.
  tox.ini
Labels: clean-up

#828 Added tests for forms and views in images plugin.
  tests/plugins/images/test_forms.py
  tests/plugins/images/test_views.py
Labels: enhancement, plugins

#826 Removed empty blocktrans template tag in a globalhistory template.
  src/wiki/plugins/globalhistory/templates/wiki/plugins/globalhistory/globalhistory.html
Labels: clean-up

#825 Use template based rendering for custom form widgets
  src/wiki/compat.py
  src/wiki/editors/markitup.py
  src/wiki/forms.py
  src/wiki/templates/wiki/forms/markitup-admin.html
  src/wiki/templates/wiki/forms/markitup.html
  src/wiki/templates/wiki/forms/select.html
  src/wiki/templates/wiki/forms/select_option.html
  src/wiki/templates/wiki/forms/text.html
Labels: clean-up, enhancement
