Repository django-wiki/django-wiki, pull requests merged in 2022-12, with the labels that each got.

#1238 Add Discussion templates
  .github/DISCUSSION_TEMPLATE/bug-report.yml
  .github/DISCUSSION_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATES/bug_report.md
Labels: enhancement

#1240 Use SHOW_MAX_CHILDREN in ArticleMixin
  README.rst
  src/wiki/views/mixins.py
  tests/core/test_views.py
Labels: bug

#1241 Re-enable CodeCov?
  .coveragerc
  pyproject.toml
Labels: clean-up
