Repository django-wiki/django-wiki, pull requests merged in 2023-02, with the labels that each got.

#1260 Remove sqlite database and use fixtures
  .gitignore
  testproject/testproject/db/prepopulated.db
  testproject/testproject/fixtures/fixtures.json
  testproject/testproject/settings/base.py
  testproject/testproject/settings/customauthuser.py
Labels: enhancement

#1264 Add support for the latest bleach version
  pyproject.toml
  src/wiki/conf/settings.py
  src/wiki/core/markdown/__init__.py
Labels: enhancement, dependencies

#1267 Add settings and middleware for demo
  testproject/testproject/fixtures/fixtures.json
  testproject/testproject/middleware.py
  testproject/testproject/settings/demo.py
Labels: enhancement

#1271 Bunch of README updates
  README.rst
Labels: documentation
