Repository django-wiki/django-wiki, pull requests merged in 2023-05, with the labels that each got.

#1283 Improve Read The Docs configuration
  .readthedocs.yml
  pyproject.toml
  requirements_readthedocs.txt
Labels: enhancement, documentation

#1284 Update languages + update to use the new Transifex client in Docker
  .tx/config
  pyproject.toml
  src/wiki/locale/fr/LC_MESSAGES/django.mo
  src/wiki/locale/ja/LC_MESSAGES/django.mo
  src/wiki/locale/ko_KR/LC_MESSAGES/django.mo
  src/wiki/locale/pt_BR/LC_MESSAGES/django.mo
  src/wiki/locale/pt_PT/LC_MESSAGES/django.mo
Labels: bug, enhancement

#1287 Update release notes and bump version to 0.10
  docs/release_notes.rst
  src/wiki/__about__.py
Labels: documentation
