Repository django-wiki/django-wiki, pull requests merged in 2023-10, with the labels that each got.

#1306 Docs: Add introduction to installation section
  docs/installation.rst
Labels: documentation

#1304 Update TOC macro to enable feature parity with Article List
  src/wiki/plugins/macros/mdx/macro.py
  src/wiki/plugins/macros/mdx/toc.py
  tests/plugins/macros/test_toc.py
Labels: enhancement

#1313 Python markdown 34 support
  pyproject.toml
  src/wiki/core/markdown/mdx/codehilite.py
  src/wiki/core/markdown/mdx/responsivetable.py
  src/wiki/plugins/attachments/markdown_extensions.py
  src/wiki/plugins/images/markdown_extensions.py
  src/wiki/plugins/links/mdx/djangowikilinks.py
  src/wiki/plugins/links/mdx/urlize.py
  src/wiki/plugins/macros/mdx/macro.py
  src/wiki/plugins/macros/mdx/toc.py
  src/wiki/plugins/macros/mdx/wikilinks.py
  tests/plugins/macros/test_toc.py
Labels: dependencies
